account/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^create-user/$', views.create_user, name='create_user'),
    url(r'^add-users$', views.add_users, name='add_users'),
    url(r'^add-refugee$', views.add_refugee, name='add_refugee'),
    url(r'^add-merchant$', views.add_merchant, name='add_merchant'),
    url(r'^add-partner-user$', views.add_partner_user, name='add_partner_user'),
    url(r'^activate-account/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
    views.activate_account, name='activate_account'),
    url(r'^add-trucker', views.add_trucker, name='add_trucker'),
    url(r'^kodhi-login/', views.kodhi_login, name='kodhi_login'),
    url(r'^enter-token/$', views.enter_token, name='enter_token'),
    url('^', include('django.contrib.auth.urls')),
]

hyper/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
				# url(r'^add-person/$', views.add_person, name='add_person'),
				url(r'^add-item/$', views.add_item, name='add_item'),
				url(r'^submit-transaction/$', views.submit_transaction, name='submit_transaction'),
				url(r'^make-trade/$', views.make_trade, name='make_trade'),
				# url(r'^participants/$', views.participants, name='participants'),
				url(r'^dashboard/$', views.dashboard, name='dashboard'),
				url(r'^$', views.login_page, name='login_page'),
				url(r'^item-detail/(?P<item_id>[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})/$', 
				views.get_item_detail, name = 'item_detail'),
				url(r'^add-shipment', views.add_shipment, name='add_shipment'),
				url(r'^shipment-detail/(?P<shipment_number>[0-9]+)/$', views.get_shipment_detail, name='shipment_detail')
				]

testapi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'app/^admin/', admin.site.urls),
    url(r'^app/', include('hyper.urls', namespace='hyper')),
    url(r'^app/account/', include('account.urls', namespace='account')),
    url(r'^app/location/', include('location.urls', namespace='location')),
    url(r'^app/analytics/', include('analytics.urls', namespace='analytics'))
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hyper/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import uuid
import qrcode
import StringIO

from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django.core.files import File
from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile

# Create your models here.
class Person(models.Model):
	ROLE_CHOICES = [
		('refugee','Refugee'),
		('vendor','Vendor'),
		('distributor','Distributor'),
		('implementor','Implementing Partner')]


	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	first_name =models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	role = models.CharField(max_length=20, choices =ROLE_CHOICES)
	balance = models.IntegerField(default=0)

	def __str__(self):
		return self.first_name + ' ' + self.last_name

class Item(models.Model):
	# item_id = models.UUIDField(default=uuid.uuid4, editable=False)
	id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=300)
	quantity = models.DecimalField(max_digits=6, decimal_places=2)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	qrcode = models.ImageField(upload_to='qrcode', blank=True, null=True)

	def get_absolute_url(self):
		return reverse('hyper:item_detail', args=[str(self.id)])

	def generate_qrcode(self):
		qr = qrcode.QRCode(version=1,error_correction=qrcode.constants.ERROR_CORRECT_L,box_size=6,border=0,)
		qr.add_data(self.get_absolute_url())
		qr.make(fit=True)
		img = qr.make_image()
		file_name = 'item_{}.png'.format(self.id)
		buffer = StringIO.StringIO()
		img.save(buffer)
		file_buffer = InMemoryUploadedFile(buffer, None, file_name, 'image/png', buffer.len, None)
		self.qrcode.save(file_name, file_buffer)


	def __str__(self):
		return '%s#%s' %(self.name, self.id)


class Shipment(models.Model):
	shipment_id = models.UUIDField(default=uuid.uuid4, editable=False)

	def get_absolute_url(self):
		return reverse('hyper:shipment_details', args=[str(self.id)])

	def __str__(self):
		return 'Shipment-{}'.format(self.id)

hyper/forms.py
from django import forms

from .models import Person, Item

#Model Form for the diferent persons
class PersonForm(forms.ModelForm):
	class Meta:
		model = Person
		fields = ('first_name', 'last_name', 'role')
		widgets = {
			'first_name':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Person\'s first name'}),
			'last_name':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Person\'s last name'}),
			'role':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Person\'s role'})
		}



#Model Form for the Items to be transferred
class ItemForm(forms.ModelForm):
	class Meta:
		model = Item
		fields =('name', 'description', 'quantity', 'owner')
		widgets = {
			'name':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Name of the item'}),
			'description':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Describe the item'}),
			'quantity':forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Amount of the item'}),
			'owner':forms.Select(attrs={'class':'form-control', 'placeholder':'Person\'s ID'})
		}

#Form for adding a new Shipment
class ShipmentForm(forms.Form):
	LOCATION_CHOICES = (
		('Head','Head Office'),
		('KlaWH', 'Kampala Warehouse'),
		('Arua','Arua Office'),
		('Yumbe','Yumbe Office'),
		('Moroto','Moroto Office')
	)
	items = forms.CharField(max_length=1000, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Items'}))
	start_location = forms.CharField(widget=forms.Select(choices=LOCATION_CHOICES, attrs={'class':'form-control', 'placeholder':'Start Location'}))
	destination = forms.CharField(widget = forms.Select(choices=LOCATION_CHOICES, attrs={'class':'form-control', 'placeholder':'Destination'}))
	# # widgets ={
	# # 	'items':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Items'}),
	# # 	'start_location': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Start Location'}),
	# # 	'destination' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Destination'})

	# }
	# trucker = forms.ChoiceField(choices=)

#Form for making a transaction
class TransactionForm(forms.Form):
	#sender = forms.CharField(max_length=40, widget = forms.TextInput(attrs={'class':'form-control', 'placeholder':'Sender ID'})) #takes the sender id
	recipient = forms.CharField(max_length=40, widget = forms.TextInput(attrs={'class':'form-control','placeholder':'Recipient ID'})) # takes the recipient id
	amount = forms.IntegerField(widget= forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Amount to transfer'}))

class TradeForm(forms.Form):
	#sender = forms.CharField(max_length=40, widget = forms.TextInput(attrs={'class':'form-control','placeholder':'Sender ID'})) #takes the sedner id
	item = forms.CharField(max_length=40, widget= forms.NumberInput(attrs={'class':'form-control','placeholder':'Item ID'})) #takes the item id
	recipient = forms.CharField(max_length=40, widget = forms.TextInput(attrs={'class':'form-control','placeholder':'Recipient ID'})) #takes the recipient id

hyper/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from .forms import PersonForm, ItemForm, TransactionForm, TradeForm, ShipmentForm
from .models import Person, Item, Shipment
from django.http import HttpResponse
from django.conf import settings
from account.forms import ActivateAccountForm
from django.contrib.auth.models import User

import requests
import os
import sys

def add_item(request):
	section_name = 'Item'
	if request.method == 'POST':
		form = ItemForm(request.POST)

		if form.is_valid():
			new_item = form.save()

			data =   {
    			"$class": "org.kibaati.Item",
    			"itemName": new_item.name,
    			"itemId": new_item.id,
    			"description": new_item.description,
    			"quantity": new_item.quantity,
    			"owner": "resource:org.kibaati.Person#" + str(new_item.owner.id)
  				}

  			# Post the new Item to the blockchain network
  			#r= requests.post('http://{}/api/Item'.format(settings.BLOCKCHAIN_URL), data=data, cookies =cookies)

  			#return HttpResponse('%s: Item added successfully' % r.status_code)

			cookies = request.COOKIES
			print 'First'
  			# Post the new Item to the blockchain network
			try:
  				r= requests.post('http://{}/api/Item'.format(settings.BLOCKCHAIN_URL), data=data, cookies=cookies)
				print r.status_code
				if r.status_code / 100 != 2:
					raise ValueError('Something went wrong')
			except ValueError as error:
				return HttpResponse(r.text)
			except:
				print("Unexpected error:", sys.exc_info()[0])
				return HttpResponse("Unexpected error:", sys.exc_info()[0])
				raise


			print 'Second'
			try:
				r = requests.get('http://{}/api/Item'.format(settings.BLOCKCHAIN_URL), cookies=cookies)
				print r.status_code
				if r.status_code / 100 != 2:
					raise ValueError('Something went wrong')
			except ValueError as error:
				return HttpResponse(r.text)
			except:
				print("Unexpected error:", sys.exc_info()[0])
				return HttpResponse("Unexpected error:", sys.exc_info()[0])
				raise

			print 'Here'


			return render(request, 'hyper/add_item.html', {'form':form, 'section_name':section_name, 'items':r.json() } )


	else:
		form = ItemForm()
		section_name ="Add an Item"
		cookies = request.COOKIES

		try:
			r = requests.get('http://{}/api/Item'.format(settings.BLOCKCHAIN_URL), cookies=cookies)
			if r.status_code / 100 != 2:
				raise ValueError('Something went wrong')
		except ValueError as error:
				return HttpResponse(r.text)
		except:
				print("Unexpected error:", sys.exc_info()[0])
				raise
		items = r.json()
			
		for b,a in enumerate(items):
			owner = a['owner'].split('#')[-1]
			items[b]['owner'] = owner
			# items[b]['owner'] = User.objects.get(pk=int(owner))
			print items[b]['owner']


		return render(request, 'hyper/add_item.html', {'form':form, 'section_name':section_name, 'items':items } )


def get_item_detail(request, item_id):
	cookies = request.COOKIES
	# item = requests.get('http://{}/api/Item'.format(settings.HYPER_SERVER), cookies=cookies)
	item = get_object_or_404(Item, id = item_id)

	return render(request, 'hyper/item_detail.html', {'item':item, 'section_name': 'Item Detail'} )


def add_shipment(request):
	section_name = 'Shipment'
	if request.method == 'POST':
		form = ShipmentForm(request.POST)

		if form.is_valid():
			cd = form.cleaned_data
			items = cd['items']
			start = cd['start_location']
			destination = cd['destination']

			shipment = Shipment()

			data = {
					"$class": "org.kibaati.Shipment",
					"shipmentId": str(shipment.shipment_id),
					"itemList": [items],
					"location": start,
					"locationReadings": [start],
					"destination": destination,
			}

			cookies = request.COOKIES

  			# Post the new Item to the blockchain network
			try:
  				r= requests.post('http://{}/api/Shipment'.format(settings.HYPER_SERVER), data=data, cookies=cookies)
				if r.status_code / 100 != 2:
					raise ValueError('Something went wrong')
			except ValueError as error:
				return HttpResponse(r.text)
			except:
				print("Unexpected error:", sys.exc_info()[0])
				raise
				# return HttpResponse("Unexpected error:", sys.exc_info()[0])

			try:
				r = requests.get('http://{}/api/Item'.format(settings.BLOCKCHAIN_URL), cookies=cookies)
				if r.status_code / 100 != 2:
					raise ValueError('Something went wrong')
			except ValueError as error:
				return HttpResponse(r.text)
			except:
				print("Unexpected error:", sys.exc_info()[0])
				raise
				# return HttpResponse("Unexpected error:", sys.exc_info()[0])

			return render(request, 'hyper/add_shipment.html', {'form':form, 'section_name':section_name } )


	else:
		form = ShipmentForm()
		cookies = request.COOKIES

		try:
			r = requests.get('http://{}/api/Shipment'.format(settings.BLOCKCHAIN_URL), cookies=cookies)
			if r.status_code / 100 != 2:
				raise ValueError('Something went wrong')
		except ValueError as error:
				return HttpResponse(r.text)
		except:
				print("Unexpected error:", sys.exc_info()[0])
				# return HttpResponse("Unexpected error:", sys.exc_info()[0])
				raise

		return render(request, 'hyper/add_shipment.html', {'form':form, 'section_name':section_name, 'shipmentd':r.json() } )
	

def get_shipment_detail(request, shipment_number):
	cookies = request.COOKIES
	# item = requests.get('http://{}/api/Item'.format(settings.HYPER_SERVER), cookies=cookies)
	shipment = get_object_or_404(Shipment, id = shipment_number)
	shipment_id = shipment.shipment_id

	shipment = requests.get('http://{}/api/Shipment/{}'.format(settings.HYPER_SERVER, shipment_id), cookies=cookies)
	shipment = shipment.json()	

	return render(request, 'hyper/shipment_detail.html', {'shipment':shipment, 'section_name': 'Shipment Detail'} )


#view that transfers money from one person to another
def submit_transaction(request):
	if request.method=='POST':
		form = TransactionForm(request.POST)

		if form.is_valid():
			cd = form.cleaned_data
			recipient = cd['recipient']
			amount = cd['amount']

			data = {
    			"$class": "org.kibaati.OrdinaryPayment",
    			"amount": amount,
    			"recipient": "resource:org.kibaati.Person#" + str(recipient),
    			}

		cookies = request.COOKIES

		try:
			r = requests.post('http://{}/api/OrdinaryPayment'.format(settings.BLOCKCHAIN_URL), data=data, cookies=cookies)
			if r.status_code / 100 != 2:
				raise ValueError('Something went wrong')
		except ValueError as error:
			return HttpResponse(r.text)
		except:
			print("Unexpected error:", sys.exc_info()[0])
			# return HttpResponse("Unexpected error:", sys.exc_info()[0])
			raise

    		return HttpResponse('%s: Payment submitted successfully' % r.status_code)

	else:
		form = TransactionForm()
		section_name ="Submit a Transaction"
		cookies = request.COOKIES
		try:
			r = requests.get('http://{}/api/OrdinaryPayment'.format(settings.BLOCKCHAIN_URL), cookies=cookies)
			if r.status_code / 100 != 2:
				raise ValueError('Something went wrong')
		except ValueError as error:
			return HttpResponse(r.text)
		except:
			print("Unexpected error:", sys.exc_info()[0])
			# return HttpResponse("Unexpected error:", sys.exc_info()[0])
			raise
		
		payments= r.json()

		return render(request, 'hyper/submit_transaction.html',{'form':form, 'section_name':section_name,'payments':payments })



#view that transfers an item from one person to another
def make_trade(request):
	if request.method=='POST':
		form = TradeForm(request.POST)

		if form.is_valid():
			cd = form.cleaned_data
			recipient = cd['recipient']
			item = cd['recipient']

			data = {
    			"$class": "org.kibaati.ItemTransfer",
    			"item": "resource:org.kibaati.Item#" + str(item),
    			"newOwner": "resource:org.kibaati.Person#" + str(recipient),
    			}
		cookies = request.COOKIES

		try:
			r= requests.post('http://{}/api/ItemTransfer'.format(settings.BLOCKCHAIN_URL),cookies =cookies, data=data)
			if r.status_code / 100 != 2:
				raise ValueError('Something went wrong')
		except ValueError as error:
			return HttpResponse(r.text)
		except:
			print("Unexpected error:", sys.exc_info()[0])
			# return HttpResponse("Unexpected error:", sys.exc_info()[0])
			raise

    		return HttpResponse('%s: Trade submitted successfully' % r.status_code)

	else:
		form = TradeForm()
		section_name = "Make a Trade"
		cookies= request.COOKIES
		try:
			r= requests.get('http://{}/api/ItemTransfer'.format(settings.BLOCKCHAIN_URL),cookies =cookies)
			if r.status_code / 100 != 2:
				raise ValueError('Something went wrong')
		except ValueError as error:
			return HttpResponse(r.text)
		except:
			print("Unexpected error:", sys.exc_info()[0])
			# return HttpResponse("Unexpected error:", sys.exc_info()[0])
			raise
		
		transfers = r.json()

		return render(request, 'hyper/make_trade.html', {'form':form, 'section_name':section_name, 'transfers':transfers})




def dashboard(request):
	# required_cookies = ['access_token','connect.sid', 'user_id']
	cookies = request.COOKIES
	for (key, value) in cookies.items():
		request.session[key] = value
        print cookies.items(), request.session.items()

	try:
		r = requests.get('http://{}/api/wallet'.format(settings.HYPER_SERVER), cookies=cookies)
		if r.status_code / 100 != 2:
			raise ValueError('Something went wrong')
	except ValueError as error:
		return HttpResponse(r.text)
	except:
		print("Unexpected error:", sys.exc_info()[0])
		# return HttpResponse("Unexpected error:", sys.exc_info()[0])
		raise

	wallet = r.json()

	if not wallet:
		return render(request, 'account/enter_token.html', {'section_name':'Import Token', 'form':ActivateAccountForm() } )
	
	return render(request, 'hyper/dashboard.html')
	# return HttpResponse(request.COOKIES.items())

def login_page(request):
	return render(request, 'account/kodhi_login.html')

hyper/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap core CSS -->

	  <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <script src="http://cdn.ckeditor.com/4.6.1/standard/ckeditor.js"></script>

    <!--Graphs -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

  </head>
  <body style="font-family:'Raleway', sans-serif">

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">KODHI</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <!--<li><a href="#">Welcome, Timo</a></li>
            <li><a href="#">Logout</a></li>-->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <header id="header">
      <div class="container">
        <div class="row">
          <div class="col-md-10">
            <h3><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Assets</h3>
          </div>
          <div class="col-md-2"> 
            {% block add_button %}{% endblock add_button %}
          </div>
        </div>
      </div>
    </header>

    <section id="main">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
             <div class="list-group">
              <a href="{% url 'hyper:dashboard' %}" class="list-group-item"></span> Dashboard</a>
              <a href="{% url 'hyper:add_item' %}" class="list-group-item active main-color-bg">Assets </a>
              <a href="{% url 'account:add_users' %}" class="list-group-item">User Management</a>
              <a href="{% url 'hyper:submit_transaction' %} " class="list-group-item "> Payments</a>
              <a href="{% url 'hyper:make_trade' %} " class="list-group-item">Trades</a>
              <a href="{% url 'account:create_user' %}" class="list-group-item">Add User</a>
            </div>
            <div class="well"></div>
          </div>

          <div class="col-md-9">
            <!-- Website Overview -->
            <div class="panel panel-default">
              <div class="panel-heading main-color-bg">
                <h3 class="panel-title">{% block section_title %}{% endblock %}</h3>
              </div>
              <div class="panel-body">
                {% block content %}{% endblock %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>


        <!-- Modals -->


    <!-- Add Page -->
    <div class="modal fade" id="addPage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                  {% block form %}{% endblock form %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add {{ section_name }} Form</h4>
                </div>
                <div class="modal-body">
                    {% block add_form %}{% endblock add_form %}
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
                </div>
                </form>
                </div>
            </div>
        </div>



    <script>
        CKEDITOR.replace( 'editor1' );
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>